tinymce.addI18n('tooltips',{
"Redo": "Redo (Ctrl+Y or Ctrl+Shift+Z)",
"Undo": "Undo (Ctrl+Z)",
"Cut": "Cut (Ctrl+X)",
"Copy": "Copy (Ctrl+C)",
"Paste": "Paste (Ctrl+V)",
"Select all": "Select all (Ctrl+A)",
"New document": "New (Ctrl+N)",
"Bold": "Bold (Ctrl+B)",
"Italic": "Italic (Ctrl+I)",
"Underline": "Underline (Ctrl+U)",
"Strikethrough": "Strikethrough (Alt+Shift+5)",
"Superscript": "Superscript (Ctrl+.)",
"Subscript": "Subscript (Ctrl+,)",
"Clear formatting": "Clear formatting (Ctrl+\\)",
//"Bullet list": "Bullet list",
//"Numbered list": "Numbered list",
"Insert/edit link": "Insert/edit link (Ctrl+K)",
"Close": "Close (Ctrl+W)",
//"Code": "Code",
//"Blockquote": "Blockquote",
//"Source code": "Source code",
"Insert link (if link plugin activated)": "Insert link (Ctrl+K)",
"Save (if save plugin activated)": "Save (Ctrl+S)",
"Horizontal line": "Horizontal line",
"Insert image": "Insert image",
"Image...": "Imagen...",
"Link...": "Link... (Ctrl+K)",
"Paste as text": "Paste as text (Shift+Ctrl+V)",
"Print...": "Print... (Ctrl+P)",
"Save": "Save (Ctrl+S)",
"Preferences": "Preferences",
"Special character": "Special character",
"Code sample": "Code sample",
"Insert link": "Insert link (Ctrl+K)",
"Link": "Link (Ctrl+K)",
"Print": "Print (Ctrl+P)",
"Find and replace": "Find and replace (Ctrl+F or Ctrl+H)",
});

